### ISSUE TITLE
Illustrator?

### ISSUE THREAD

**Issue by yangchenghu** [Phunk87/VectorPDFSupportTest#2]
Illustrator?

**Comment by Phunk87** [comment]
Yeah, you can find out how to do it from Illustrator help. REF: http://helpx.adobe.com/illustrator/using/creating-pdf-files.html

**Comment by yangchenghu** [comment]
Thx :+1:

**Comment by Phunk87** [comment]
My pleasure.

**Comment by yangchenghu** [comment]
gemen, u have a wrong word "Illustrtor" -> "Illustrator"

**Comment by Phunk87** [comment]
I see, i will fix it. Thx.
