### ISSUE TITLE
PDF文件太大啊

### ISSUE THREAD

**Issue by hyhSuper** [Phunk87/VectorPDFSupportTest#3]
一般的图片很小，但是一旦转化成pdf文件，就会变的很大。这个问题会造成，应用宝特别大啊。所以这个方法不太实用啊

**Comment by Phunk87** [comment]
PDF 本身不会被打包进 App, Xcode 会根据 PDF 根据不同分辨率自动转化为对应的 PNG 图片。这里减少的是设计产出和开发维护图片资源的心智负担。

**Comment by hyhSuper** [comment]
有官方文档链接啊？可以给发一份好吗？

**Comment by Phunk87** [comment]
遗憾的是，苹果官方的 Asset Catalogs Guide 中并没有特别的支出 PDF Vector 的支持。
这一特性主要是通过 WWDC 2014 的 411 期指出的，具体见下图：

![4a25de15-afc2-4ff3-8f8e-39221e4e3f8c](https://cloud.githubusercontent.com/assets/907754/10411856/03993e96-6fa6-11e5-8719-05da8313c862.png)

[WWDC 2014-411 视频](https://developer.apple.com/videos/play/wwdc2014-411/) 点这里。

**Comment by Phunk87** [comment]
BTW, 如果你觉得生成的 PDF 太大，在版本管理时每次新增延长了 push 时间，并且增加了太多的项目存储空间，可以通过 http://smallpdf.com 这个网站来对 PDF 文件做压缩。
